version: '3.8'

services:  
  db:
    image: mysql:latest # use latest version of mysql
    container_name: testdb # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: testdb # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
  app:
    container_name: app
    restart: always
    build: 
      context: . # NATE investigate - added the ':'
      dockerfile: Dockerfile
      target: build
    env_file: .env
    command: npm run dev
    ports:
      - 3000:3000
    depends_on:
      - db

volumes: # add persistent data even if container is removed.
  my-db: